#!/usr/bin/env bats
# Tests for lib/omp-reviewer.sh + the OMP routing in code-review-subagent.sh /
# propose-rules.sh — the no-Anthropic stop guarantee (hooks.md: "OMP owns its
# stop event. Any model-backed hook reached from that event MUST use the live
# non-Anthropic eval/role-resolver route … or skip the model rung").
#
# The invariant under test: when TRELLIS_OMP=1, NO test path can reach a
# `claude` binary. Every test plants a `claude` stub on PATH that WRITES A
# TOMBSTONE if executed; a pass requires the tombstone to be absent.
#
# PORTABLE / MIRROR-CLEAN: fixtures under mktemp; no absolute machine paths;
# no network; the real `claude` and real `omp` are never invoked.

load helpers

# One-line findings validator (local copy of the ladder suite's helper).
assert_valid_findings() {
  if command -v jq >/dev/null 2>&1; then
    echo "$output" | jq -e 'type == "object" and (.findings | type == "array")' >/dev/null
  else
    [[ "$output" == *'{"findings":'* ]] || { echo "$output"; false; }
  fi
}

LIB="$HOOKS_DIR/lib/omp-reviewer.sh"
HOOK="$HOOKS_DIR/code-review-subagent.sh"
SESSION_HOOK="$HOOKS_DIR/herdr-foreman-session.sh"

REVIEW_INPUT='diff --git a/fixture.txt b/fixture.txt
--- a/fixture.txt
+++ b/fixture.txt
@@ -0,0 +1 @@
+fixture reviewer input'

# --- fixture builders ------------------------------------------------------

# A claude stub that records its own execution into $TOMBSTONE. If this file
# exists after a hook run, a Claude process was reachable — the invariant broke.
make_tombstone_claude() {
  local dir stub
  dir="$(mktemp -d "$BATS_TMPDIR/ompclaude.XXXXXX")"
  stub="$dir/claude"
  {
    printf '#!/usr/bin/env bash\n'
    printf 'printf "CLAUDE_REACHED\\n" >> "%s"\n' "$TOMBSTONE"
    printf 'printf \x27{"findings":[]}\x27\\n'
  } >"$stub"
  chmod +x "$stub"
  printf '%s' "$dir"
}

# An omp stub that behaves like `omp -p` for the reviewer route: reads stdin,
# prints a findings line, records that it ran and the model argv it received.
make_omp_stub() {
  local dir out="$1"
  dir="$(mktemp -d "$BATS_TMPDIR/ompstub.XXXXXX")"
  cat >"$dir/omp" <<EOF
#!/usr/bin/env bash
cat >/dev/null
{
  printf 'RAN_OMP\n'
  printf 'ARGS'
  printf '\t%s' "\$@"
  printf '\n'
} >> "$out"
printf '{"findings":[]}\n'
EOF
  chmod +x "$dir/omp"
  printf '%s' "$dir"
}

make_session_resolver_stubs() {
  local dir
  dir="$(mktemp -d "$BATS_TMPDIR/resolverstubs.XXXXXX")"
  cat >"$dir/omp" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
  usage)
    printf '%s\n' '{"reports":[{"provider":"openai-codex","limits":[{"id":"shared","amount":{"remainingFraction":0.9}}]},{"provider":"xai-oauth","limits":[{"id":"shared","amount":{"remainingFraction":0.9}}]},{"provider":"opencode-go","limits":[{"id":"shared","amount":{"remainingFraction":0.9}}]},{"provider":"nous-portal","limits":[{"id":"shared","amount":{"remainingFraction":0.9}}]},{"provider":"meta","limits":[{"id":"shared","amount":{"remainingFraction":0.9}}]},{"provider":"google-antigravity","limits":[{"id":"shared","amount":{"remainingFraction":0.9}}]}],"disabledCredentials":[]}'
    ;;
  token)
    printf 'fixture-token\n'
    ;;
  *)
    exit 64
    ;;
esac
EOF
  cat >"$dir/herdr" <<'EOF'
#!/usr/bin/env bash
if [ "${1:-}" = agent ] && [ "${2:-}" = list ]; then
  printf '{"result":{"agents":[]}}\n'
  exit 0
fi
exit 64
EOF
  chmod +x "$dir/omp" "$dir/herdr"
  printf '%s' "$dir"
}



# Create an active-release roles policy. The reviewer route must ignore every
# project/legacy lookalike and discover exactly this payload through
# TRELLIS_HOME/config.json.
make_active_release_policy() {
  local home="$1" release="1.2.3"
  local policy="$home/.trellis/releases/$release/payload/core-rules/skills/herdr-foreman/roles.json"

  mkdir -p "$(dirname "$policy")"
  cp "$HOOKS_DIR/../skills/herdr-foreman/roles.json" "$policy"
  printf '{"active_cli_release":"%s"}\n' "$release" >"$home/.trellis/config.json"
  chmod 600 "$home/.trellis/config.json"
  printf '%s' "$policy"
}

make_active_release_resolver() {
  local home="$1" policy resolver
  policy="$(make_active_release_policy "$home")"
  resolver="$(dirname "$policy")/scripts/resolve-roles.py"
  mkdir -p "$(dirname "$resolver")"
  cp "$HOOKS_DIR/../skills/herdr-foreman/scripts/resolve-roles.py" "$resolver"
  printf '%s' "$resolver"
}

# A production-catalog deciding artifact generated by the copied resolver with
# deterministic usage/auth stubs. The live six-family roster is a partial:
# merge_reviewer and refuter degrade, approval_ready stays false, and reviewer
# remains independently consumable.
make_deciding_reviewer_state() {
  local home="$1"
  local nonce="${2:-fixture-workspace:fixture-pane:fixture-pass}"
  local workspace="${3:-fixture-workspace}"
  local pane="${4:-fixture-pane}"
  local state="$home/.omp/agent/roles-resolved.json"
  local resolver
  resolver="$(make_active_release_resolver "$home")"

  mkdir -p "$(dirname "$state")"
  python3 - "$resolver" "$home" "$nonce" "$workspace" "$pane" <<'PY'
import contextlib
import importlib.util
import io
import os
import sys

resolver_path, home, nonce, workspace, pane = sys.argv[1:]
os.environ["HOME"] = home
os.environ["TRELLIS_HOME"] = os.path.join(home, ".trellis")
os.environ["HERDR_ENV"] = "1"
os.environ["HERDR_WORKSPACE_ID"] = workspace
os.environ["HERDR_PANE_ID"] = pane
os.environ["HERDR_RESOLUTION_NONCE"] = nonce

usage = {
    "reports": [
        {
            "provider": "openai-codex",
            "limits": [{"id": "shared", "amount": {"remainingFraction": 0.9}}],
        },
        {
            "provider": "xai-oauth",
            "limits": [{"id": "shared", "amount": {"remainingFraction": 0.9}}],
        },
        {
            "provider": "opencode-go",
            "limits": [{"id": "shared", "amount": {"remainingFraction": 0.9}}],
        },
        {
            "provider": "nous-portal",
            "limits": [{"id": "shared", "amount": {"remainingFraction": 0.9}}],
        },
        {
            "provider": "meta",
            "limits": [{"id": "shared", "amount": {"remainingFraction": 0.9}}],
        },
        {
            "provider": "google-antigravity",
            "limits": [{"id": "shared", "amount": {"remainingFraction": 0.9}}],
        },
    ],
    "disabledCredentials": [],
}

spec = importlib.util.spec_from_file_location("rr", resolver_path)
rr = importlib.util.module_from_spec(spec)
spec.loader.exec_module(rr)
rr.load_usage = lambda ttl, fresh, usage_source="omp": (usage, "fixture")
rr.auth_probe_passes = lambda candidate, cache: True
sys.argv = [resolver_path, "--implementer", "luna"]
with contextlib.redirect_stdout(io.StringIO()):
    rr.main()
PY
  chmod 600 "$state"
  printf '%s' "$state"
}

assert_omp_reviewer_fail_closed() {
  local fake_home="$1"
  local workspace="${2:-fixture-workspace}"
  local pane="${3:-fixture-pane}"
  local marker stub_dir path_backup claude_dir
  marker="$(mktemp "$BATS_TMPDIR/failclosed.XXXXXX")"
  stub_dir="$(make_omp_stub "$marker")"
  path_backup="$PATH"
  claude_dir="$(make_tombstone_claude)"
  export PATH="$stub_dir:$claude_dir:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    HOME="$fake_home" TRELLIS_HOME="$fake_home/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID="$workspace" HERDR_PANE_ID="$pane" \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$path_backup"
  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$marker" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$stub_dir" "$claude_dir"
  rm -f "$marker"
}

setup_tombstone() {
  TOMBSTONE="$(mktemp "$BATS_TMPDIR/tomb.XXXXXX")"
  : >"$TOMBSTONE"
}

teardown_tombstone() {
  [ -n "${TOMBSTONE:-}" ] && rm -f "$TOMBSTONE"
}

# =========================================================================
# lib/omp-reviewer.sh unit behavior
# =========================================================================

@test "omp-reviewer: execs CODE_REVIEWER_CMD with untouched stdin" {
  setup_tombstone
  OP_MARKER="$(mktemp "$BATS_TMPDIR/opmark.XXXXXX")"
  dir="$(mktemp -d "$BATS_TMPDIR/oprev.XXXXXX")"
  cat >"$dir/myreviewer" <<EOF
#!/usr/bin/env bash
cat
printf '%s\n' '{"findings":[{"severity":"important","file":"a","line":1,"msg":"from-operator"}]}'
printf "OPERATOR_RAN\n" >>"$OP_MARKER"
EOF
  chmod +x "$dir/myreviewer"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$CLAUDE_DIR:$PATH"
  run env CODE_REVIEWER_CMD="$dir/myreviewer" bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"
  rm -rf "$dir" "$CLAUDE_DIR"

  [ "$status" -eq 0 ]
  [[ "$output" == *'"from-operator"'* ]]
  grep -q OPERATOR_RAN "$OP_MARKER"
  rm -f "$OP_MARKER"
  # And no Claude process was reached: the tombstone records claude runs only.
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  teardown_tombstone
}

@test "omp-reviewer: missing deciding artifact fails closed without invoking omp" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  MARKER="$(mktemp "$BATS_TMPDIR/ompran.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    -u HERDR_ENV -u HERDR_WORKSPACE_ID -u HERDR_PANE_ID \
    HOME="$FAKE_HOME" bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: healthy current Herdr artifact uses its resolved model" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  MODEL="meta/muse-spark-1.2-contributor:xhigh"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

artifact = json.load(open(sys.argv[1], encoding="utf-8"))
assert artifact["approval_ready"] is False
assert artifact["resolution_scope"]["verdict_families_distinct"] is False
assert artifact["degraded_verdict_roles"] == ["merge_reviewer", "refuter"]
assert artifact["roles"]["reviewer"]["chosen"]["agent"] == "cheap"
assert artifact["roles"]["reviewer"]["chosen"]["model"] == "meta/muse-spark-1.2-contributor:xhigh"
assert artifact["roles"]["merge_reviewer"]["chosen"] is None
assert len(artifact["roles"]["refuter"]["seats"]) == 2
print("partial-ok")
PY
  [ ! -e "$FAKE_HOME/.omp/agent/agents/cheap.md" ]
  MARKER="$(mktemp "$BATS_TMPDIR/ompran.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  assert_valid_findings
  grep -q RAN_OMP "$MARKER"
  grep -qF "$MODEL" "$MARKER"
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: rejects an implementer row that diverges from its deciding scope" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  POLICY="$FAKE_HOME/.trellis/releases/1.2.3/payload/core-rules/skills/herdr-foreman/roles.json"
  python3 - "$STATE" "$POLICY" <<'PY'
import json
import sys

state_path, policy_path = sys.argv[1:]
with open(policy_path, encoding="utf-8") as source:
    policy = json.load(source)
with open(state_path, encoding="utf-8") as source:
    artifact = json.load(source)
deepseek = policy["agents"]["cheap-2"]
assert any(
    isinstance(candidate, dict) and candidate.get("agent") == "cheap-2"
    for candidate in policy["roles"]["implementer"]["chain"]
)
resolved = artifact["roles"]["implementer"]
for candidate in (resolved["chosen"], *resolved["trail"]):
    candidate.update({
        "agent": "cheap-2",
        "model": deepseek["model"],
        "provider": deepseek["provider"],
    })
with open(state_path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  MARKER="$(mktemp "$BATS_TMPDIR/scopeimpl.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: never consumes a deciding artifact outside Herdr" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  MARKER="$(mktemp "$BATS_TMPDIR/nonherdr.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  HOME_BACKUP="${HOME:-}"
  TRELLIS_HOME_BACKUP="${TRELLIS_HOME:-}"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  export HOME="$FAKE_HOME"
  export TRELLIS_HOME="$FAKE_HOME/.trellis"
  unset CODE_REVIEWER_CMD TRELLIS_OMP_REVIEW_CMD OMP_ROLE_STATE
  unset HERDR_ENV HERDR_WORKSPACE_ID HERDR_PANE_ID
  unset TRELLIS_ROOT CLAUDE_PROJECT_DIR CODEX_PROJECT_DIR
  run_with_stderr "$LIB" "$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"
  if [ -n "$HOME_BACKUP" ]; then export HOME="$HOME_BACKUP"; else unset HOME; fi
  if [ -n "$TRELLIS_HOME_BACKUP" ]; then
    export TRELLIS_HOME="$TRELLIS_HOME_BACKUP"
  else
    unset TRELLIS_HOME
  fi

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  [[ "$stderr" == *"deciding artifact is unavailable or invalid; deterministic OMP fallback applies"* ]] || {
    echo "stderr:[$stderr]"; false;
  }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: refuses a policy-consistent resolved Anthropic model" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  POLICY="$FAKE_HOME/.trellis/releases/1.2.3/payload/core-rules/skills/herdr-foreman/roles.json"
  python3 - "$STATE" "$POLICY" <<'PY'
import hashlib
import json
import sys

state_path, policy_path = sys.argv[1:]
with open(policy_path, encoding="utf-8") as source:
    policy = json.load(source)
with open(state_path, encoding="utf-8") as source:
    artifact = json.load(source)
reviewer_agent = artifact["roles"]["reviewer"]["chosen"]["agent"]
policy["agents"][reviewer_agent].update({
    "model": "google-antigravity/claude-opus-9:xhigh",
    "effort": "xhigh",
})
with open(policy_path, "w", encoding="utf-8") as destination:
    json.dump(policy, destination)
with open(policy_path, "rb") as source:
    policy_bytes = source.read()
for candidate in (
    artifact["roles"]["reviewer"]["chosen"],
    *artifact["roles"]["reviewer"]["trail"],
):
    if candidate.get("agent") == reviewer_agent:
        candidate["model"] = "google-antigravity/claude-opus-9:xhigh"
artifact["roles_policy"] = {
    "roles_sha256": hashlib.sha256(policy_bytes).hexdigest(),
    "cache_ttl_seconds": policy["cache_ttl_seconds"],
}
with open(state_path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  MARKER="$(mktemp "$BATS_TMPDIR/nolan.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: rejects a stale deciding artifact" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
artifact["resolved_at"] = "2000-01-01T00:00:00+00:00"
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  MARKER="$(mktemp "$BATS_TMPDIR/stale.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: a foreign high-TTL project policy cannot extend stale artifact freshness" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  FOREIGN_PROJECT="$(mktemp -d "$BATS_TMPDIR/foreignpolicy.XXXXXX")"
  FOREIGN_POLICY="$FOREIGN_PROJECT/.claude/skills/herdr-foreman/roles.json"
  mkdir -p "$(dirname "$FOREIGN_POLICY")"
  cp "$HOOKS_DIR/../skills/herdr-foreman/roles.json" "$FOREIGN_POLICY"
  python3 - "$FOREIGN_POLICY" "$STATE" <<'PY'
import datetime as dt
import json
import sys

policy_path, artifact_path = sys.argv[1:]
with open(policy_path, encoding="utf-8") as source:
    policy = json.load(source)
policy["cache_ttl_seconds"] = 86400
with open(policy_path, "w", encoding="utf-8") as destination:
    json.dump(policy, destination)

with open(artifact_path, encoding="utf-8") as source:
    artifact = json.load(source)
artifact["resolved_at"] = (
    dt.datetime.now(dt.timezone.utc) - dt.timedelta(hours=3)
).isoformat(timespec="seconds")
with open(artifact_path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  MARKER="$(mktemp "$BATS_TMPDIR/highttl.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    -u TRELLIS_ROOT -u CODEX_PROJECT_DIR \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    CLAUDE_PROJECT_DIR="$FOREIGN_PROJECT" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$FOREIGN_PROJECT" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: canonical release lookup ignores a foreign high-TTL policy" {
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  ACTIVE_POLICY="$(make_active_release_policy "$FAKE_HOME")"
  ACTIVE_POLICY_REAL="$(python3 - "$ACTIVE_POLICY" <<'PY'
import os
import sys
print(os.path.realpath(sys.argv[1]))
PY
)"
  FOREIGN_PROJECT="$(mktemp -d "$BATS_TMPDIR/foreignpolicy.XXXXXX")"
  FOREIGN_POLICY="$FOREIGN_PROJECT/.claude/skills/herdr-foreman/roles.json"
  mkdir -p "$(dirname "$FOREIGN_POLICY")"
  cp "$HOOKS_DIR/../skills/herdr-foreman/roles.json" "$FOREIGN_POLICY"
  python3 - "$FOREIGN_POLICY" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as source:
    policy = json.load(source)
policy["cache_ttl_seconds"] = 86400
with open(sys.argv[1], "w", encoding="utf-8") as destination:
    json.dump(policy, destination)
PY

  run env -u TRELLIS_ROOT -u CODEX_PROJECT_DIR \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    CLAUDE_PROJECT_DIR="$FOREIGN_PROJECT" \
    bash -c 'source "$1"; _omp_reviewer_roles_config' -- "$LIB"

  [ "$status" -eq 0 ]
  [ "$output" = "$ACTIVE_POLICY_REAL" ]
  rm -rf "$FAKE_HOME" "$FOREIGN_PROJECT"
}

@test "omp-reviewer: rejects a forged family claim that masks a same-family reviewer" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
artifact["resolution_scope"]["implementer_family"] = "meta"
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  MARKER="$(mktemp "$BATS_TMPDIR/samefamily.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    -u TRELLIS_ROOT -u CLAUDE_PROJECT_DIR -u CODEX_PROJECT_DIR \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: rejects a prefix-only cross-pane artifact" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state \
    "$FAKE_HOME" \
    "this-workspace:this-pane:fixture-pass" \
    "other-workspace" \
    "other-pane")"
  MARKER="$(mktemp "$BATS_TMPDIR/crosspane.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    -u TRELLIS_ROOT -u CLAUDE_PROJECT_DIR -u CODEX_PROJECT_DIR \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=this-workspace HERDR_PANE_ID=this-pane \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: rejects a single-field tampered reviewer artifact" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
artifact["roles"]["reviewer"]["chosen"]["model"] = "openai-codex/tampered:xhigh"
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  MARKER="$(mktemp "$BATS_TMPDIR/tampered.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
  grep -q RAN_OMP "$MARKER" && { echo "omp should not have run"; false; }
  [ ! -s "$TOMBSTONE" ] || { cat "$TOMBSTONE"; false; }
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"
  teardown_tombstone
}

@test "omp-reviewer: no route at all → empty findings + rc 0 (caller degrades)" {
  PATH_BACKUP="$PATH"
  # Strip every dir that could carry omp/claude/CODE_REVIEWER_CMD targets.
  CLEAN_PATH="$(mktemp -d "$BATS_TMPDIR/cleanpath.XXXXXX")"
  for cmd in bash sh cat printf sed head tr grep mktemp env command; do
    src="$(command -v "$cmd" 2>/dev/null)" && ln -sf "$src" "$CLEAN_PATH/$cmd"
  done
  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD PATH="$CLEAN_PATH" HOME="/nonexistent" bash "$LIB" <<<"$REVIEW_INPUT"
  rm -rf "$CLEAN_PATH"

  [ "$status" -eq 0 ]
  [[ "$output" == *'{"findings":[]}'* ]] || { echo "GOT:[$output]"; false; }
}

@test "omp-reviewer: honors TRELLIS_OMP_REVIEW_CMD before the omp CLI" {
  setup_tombstone
  dir="$(mktemp -d "$BATS_TMPDIR/tocmd.XXXXXX")"
  cat >"$dir/pinned" <<EOF
#!/usr/bin/env bash
cat
printf '%s\n' '{"findings":[{"severity":"minor","file":"z","line":1,"msg":"pinned-cmd"}]}'
EOF
  chmod +x "$dir/pinned"
  MARKER="$(mktemp "$BATS_TMPDIR/nocli.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"

  PATH_BACKUP="$PATH"
  export PATH="$STUB_DIR:$PATH"
  run env TRELLIS_OMP_REVIEW_CMD="$dir/pinned" bash "$LIB" <<<"$REVIEW_INPUT"
  export PATH="$PATH_BACKUP"
  rm -rf "$dir" "$STUB_DIR" "$MARKER"

  [ "$status" -eq 0 ]
  [[ "$output" == *'"pinned-cmd"'* ]]
  grep -q RAN_OMP "$MARKER" && { echo "CLI route should be shadowed by the pinned cmd"; false; }
  teardown_tombstone
}

@test "omp-reviewer: forwards envelope bytes untouched on stdin" {
  dir="$(mktemp -d "$BATS_TMPDIR/stdin.XXXXXX")"
  ENVELOPE='{"diff":"+x=1","autonomy_level":3,"decisions_log":""}'
  cat >"$dir/capture" <<EOF
#!/usr/bin/env bash
cat >"$dir/seen"
printf '%s\n' '{"findings":[]}'
EOF
  chmod +x "$dir/capture"
  run env TRELLIS_OMP_REVIEW_CMD="$dir/capture" bash "$LIB" <<<"$ENVELOPE"

  [ "$status" -eq 0 ]
  [ "$(cat "$dir/seen")" = "$ENVELOPE" ]
  rm -rf "$dir"
}

@test "omp-reviewer: rejects an explicitly degraded reviewer" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
reviewer = artifact["roles"]["reviewer"]
reviewer["chosen"] = None
reviewer["trail"] = []
artifact["degraded_roles"] = ["reviewer", "merge_reviewer", "refuter"]
artifact["degraded_verdict_roles"] = ["reviewer", "merge_reviewer", "refuter"]
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  assert_omp_reviewer_fail_closed "$FAKE_HOME"
  rm -rf "$FAKE_HOME"
  teardown_tombstone
}

@test "omp-reviewer: rejects a missing verdict role omitted from degraded declarations" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
artifact["degraded_roles"] = ["refuter"]
artifact["degraded_verdict_roles"] = ["refuter"]
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  assert_omp_reviewer_fail_closed "$FAKE_HOME"
  rm -rf "$FAKE_HOME"
  teardown_tombstone
}

@test "omp-reviewer: rejects a 2/3 refuter panel omitted from degraded declarations" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
artifact["degraded_roles"] = ["merge_reviewer"]
artifact["degraded_verdict_roles"] = ["merge_reviewer"]
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  assert_omp_reviewer_fail_closed "$FAKE_HOME"
  rm -rf "$FAKE_HOME"
  teardown_tombstone
}

@test "omp-reviewer: rejects forged approval_ready on a partial roster" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
artifact["approval_ready"] = True
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  assert_omp_reviewer_fail_closed "$FAKE_HOME"
  rm -rf "$FAKE_HOME"
  teardown_tombstone
}

@test "omp-reviewer: rejects forged verdict_families_distinct on a partial roster" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
artifact["resolution_scope"]["verdict_families_distinct"] = True
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  assert_omp_reviewer_fail_closed "$FAKE_HOME"
  rm -rf "$FAKE_HOME"
  teardown_tombstone
}

@test "omp-reviewer: rejects a tampered available partial refuter seat" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
seats = artifact["roles"]["refuter"]["seats"]
assert len(seats) == 2
seats.pop()
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  assert_omp_reviewer_fail_closed "$FAKE_HOME"
  rm -rf "$FAKE_HOME"
  teardown_tombstone
}

@test "omp-reviewer: rejects a non-private deciding artifact mode" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  chmod 644 "$STATE"
  assert_omp_reviewer_fail_closed "$FAKE_HOME"
  rm -rf "$FAKE_HOME"
  teardown_tombstone
}

@test "omp-reviewer: rejects malformed nested keys without leaking a traceback" {
  setup_tombstone
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  python3 - "$STATE" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as source:
    artifact = json.load(source)
del artifact["degraded_roles"]
with open(path, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
PY
  chmod 600 "$STATE"
  assert_omp_reviewer_fail_closed "$FAKE_HOME"
  rm -rf "$FAKE_HOME"
  teardown_tombstone
}


# =========================================================================
# SessionStart writer authority
# =========================================================================

@test "herdr session hook writes only an active-release-bound deciding artifact" {
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  RELEASE_RESOLVER="$(make_active_release_resolver "$FAKE_HOME")"
  POISON_PROJECT="$(mktemp -d "$BATS_TMPDIR/poisonproject.XXXXXX")"
  POISON_RESOLVER="$POISON_PROJECT/.claude/skills/herdr-foreman/scripts/resolve-roles.py"
  mkdir -p "$(dirname "$POISON_RESOLVER")"
  printf 'raise SystemExit(91)\n' >"$POISON_RESOLVER"
  CLI_DIR="$(make_session_resolver_stubs)"
  ROLE_STATE="$FAKE_HOME/.omp/agent/roles-resolved.json"
  POLICY="$FAKE_HOME/.trellis/releases/1.2.3/payload/core-rules/skills/herdr-foreman/roles.json"

  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    CLAUDE_PROJECT_DIR="$POISON_PROJECT" PATH="$CLI_DIR:$PATH" \
    bash "$SESSION_HOOK"

  [ "$status" -eq 0 ]
  [ -f "$RELEASE_RESOLVER" ]
  [ -f "$ROLE_STATE" ] || { echo "release resolver was not selected: $output"; false; }
  [[ "$output" == *"DEGRADED: refuter has 2/3 independent seats"* ]] || {
    echo "missing refuter degradation: $output"; false;
  }
  [[ "$output" == *"DEGRADED: no candidate for merge_reviewer"* ]] || {
    echo "missing merge_reviewer degradation: $output"; false;
  }
  [[ "$output" == *"route merge_reviewer, refuter to the Claude apex"* ]] || {
    echo "missing Claude-apex routing: $output"; false;
  }
  python3 - "$ROLE_STATE" "$POLICY" <<'PY'
import hashlib
import json
import sys

state_path, policy_path = sys.argv[1:]
with open(policy_path, "rb") as source:
    policy_bytes = source.read()
with open(state_path, encoding="utf-8") as source:
    artifact = json.load(source)
assert artifact["roles_policy"] == {
    "roles_sha256": hashlib.sha256(policy_bytes).hexdigest(),
    "cache_ttl_seconds": json.loads(policy_bytes)["cache_ttl_seconds"],
}
scope = artifact["resolution_scope"]
assert scope["herdr_workspace_id"] == "fixture-workspace"
assert scope["herdr_pane_id"] == "fixture-pane"
assert scope["implementer"] == "luna"
assert scope["implementer_model"] == "openai-codex/gpt-5.6-luna:max"
assert scope["implementer_provider"] == "openai-codex"
assert scope["verdict_families_distinct"] is False
chosen = artifact["roles"]["implementer"]["chosen"]
assert (
    chosen["agent"],
    chosen["model"],
    chosen["provider"],
) == (
    scope["implementer"],
    scope["implementer_model"],
    scope["implementer_provider"],
)
assert (
    json.loads(policy_bytes)["agents"][chosen["agent"]]["family"]
    == scope["implementer_family"]
)
assert artifact["approval_ready"] is False
assert artifact["family_collapse"] == []
assert artifact["degraded_verdict_roles"] == ["merge_reviewer", "refuter"]
assert artifact["roles"]["merge_reviewer"]["chosen"] is None
assert [seat["agent"] for seat in artifact["roles"]["refuter"]["seats"]] == [
    "glm-flash-go",
    "flash",
]
PY
  rm -rf "$FAKE_HOME" "$POISON_PROJECT" "$CLI_DIR"
}

@test "herdr session hook clears a deciding artifact whose implementer row diverges" {
  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  RELEASE_RESOLVER="$(make_active_release_resolver "$FAKE_HOME")"
  POLICY="$FAKE_HOME/.trellis/releases/1.2.3/payload/core-rules/skills/herdr-foreman/roles.json"
  CLI_DIR="$(make_session_resolver_stubs)"
  ROLE_STATE="$FAKE_HOME/.omp/agent/roles-resolved.json"

  # Production-shaped partial artifact: luna in scope, cheap-2 in the live
  # implementer row. Writer validation must reject the binding after schema
  # checks, not fail earlier on fixture-only families or false approval.
  cat >"$RELEASE_RESOLVER" <<'PY'
import datetime as dt
import hashlib
import json
import os
import sys

policy_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "roles.json"
)
with open(policy_path, "rb") as source:
    policy_bytes = source.read()
policy = json.loads(policy_bytes)


def candidate(role, agent):
    if not any(
        item["agent"] == agent
        for item in policy["roles"][role]["chain"]
    ):
        raise ValueError(f"{agent} is not a candidate for {role}")
    return dict(policy["agents"][agent], agent=agent)


def resolved(role, agent):
    configured = candidate(role, agent)
    chosen = {
        key: configured[key] for key in ("agent", "model", "provider")
    }
    chosen.update({"remaining": 1.0, "note": "reported"})
    return {
        "purpose": policy["roles"][role]["purpose"],
        "chosen": chosen,
        "trail": [dict(chosen, eligible=True, reason="eligible")],
        "refusals": [],
        "overflow": None,
    }


def resolved_none(role, refusal_specs):
    refusals = []
    for agent, reason in refusal_specs:
        configured = candidate(role, agent)
        refusals.append({
            "agent": configured["agent"],
            "model": configured["model"],
            "provider": configured["provider"],
            "eligible": False,
            "reason": reason,
            "remaining": None,
        })
    return {
        "purpose": policy["roles"][role]["purpose"],
        "chosen": None,
        "trail": [],
        "refusals": refusals,
        "overflow": None,
    }


def resolved_refuter(agents):
    seats = []
    for agent in agents:
        configured = candidate("refuter", agent)
        seat = {
            key: configured[key] for key in ("agent", "model", "provider")
        }
        seat.update({
            "remaining": 1.0,
            "note": "reported",
            "eligible": True,
            "reason": "eligible",
        })
        seats.append(seat)
    chosen = {
        key: seats[0][key]
        for key in ("agent", "model", "provider", "remaining", "note")
    }
    return {
        "purpose": policy["roles"]["refuter"]["purpose"],
        "chosen": chosen,
        "trail": [dict(seat) for seat in seats],
        "refusals": [],
        "overflow": None,
        "seats": seats,
        "required_seats": 3,
    }


if "--json" in sys.argv[1:]:
    print(json.dumps({
        "roles": {"implementer": {"chosen": {"agent": "luna"}}}
    }))
    raise SystemExit(0)

scope_implementer = candidate("implementer", "luna")
roles = {
    "foreman": resolved("foreman", "sol"),
    "implementer": resolved("implementer", "cheap-2"),
    "hard_implementer": resolved("hard_implementer", "luna"),
    "deep_worker": resolved("deep_worker", "glm-flash-go"),
    "scout": resolved("scout", "flash"),
    "reviewer": resolved("reviewer", "cheap"),
    "security_reviewer": resolved("security_reviewer", "security-reviewer"),
    "merge_reviewer": resolved_none("merge_reviewer", (
        ("sol", "same-family"),
        ("grok", "verdict-family-in-use"),
    )),
    "refuter": resolved_refuter(("glm-flash-go", "flash")),
}
if set(roles) != set(policy["roles"]):
    raise SystemExit("fixture roles do not match policy")
artifact = {
    "resolved_at": dt.datetime.now(dt.timezone.utc).isoformat(
        timespec="seconds"
    ),
    "resolution_nonce": os.environ["HERDR_RESOLUTION_NONCE"],
    "roles_policy": {
        "roles_sha256": hashlib.sha256(policy_bytes).hexdigest(),
        "cache_ttl_seconds": policy["cache_ttl_seconds"],
    },
    "usage_source": "fixture",
    "resolution_scope": {
        "scoped": True,
        "implementer": scope_implementer["agent"],
        "implementer_model": scope_implementer["model"],
        "implementer_provider": scope_implementer["provider"],
        "implementer_family": policy["agents"][scope_implementer["agent"]]["family"],
        "cross_family_enforced": True,
        "verdict_families_distinct": False,
        "herdr_workspace_id": os.environ["HERDR_WORKSPACE_ID"],
        "herdr_pane_id": os.environ["HERDR_PANE_ID"],
    },
    "approval_ready": False,
    "degraded_roles": ["merge_reviewer", "refuter"],
    "degraded_verdict_roles": ["merge_reviewer", "refuter"],
    "family_collapse": [],
    "roles": roles,
}
state = os.path.join(
    os.environ["HOME"], ".omp", "agent", "roles-resolved.json"
)
os.makedirs(os.path.dirname(state), exist_ok=True)
with open(state, "w", encoding="utf-8") as destination:
    json.dump(artifact, destination)
os.chmod(state, 0o600)
PY

  run env -u CODE_REVIEWER_CMD -u TRELLIS_OMP_REVIEW_CMD -u OMP_ROLE_STATE \
    HOME="$FAKE_HOME" TRELLIS_HOME="$FAKE_HOME/.trellis" \
    HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane \
    PATH="$CLI_DIR:$PATH" bash "$SESSION_HOOK"

  [ "$status" -eq 0 ]
  [ ! -e "$ROLE_STATE" ] || {
    echo "scope-divergent deciding artifact was not cleared"
    false
  }
  rm -rf "$FAKE_HOME" "$CLI_DIR"
}


# =========================================================================
# code-review-subagent.sh routing under TRELLIS_OMP=1
# =========================================================================

@test "code-review-subagent under TRELLIS_OMP=1 inside Herdr routes to omp-reviewer, never claude" {
  setup_project_dir
  setup_tombstone
  (
    cd "$PROJECT_DIR" || exit 1
    printf 'def a():\n    return 1\n' >a.py
    printf 'def b():\n    return 2\n' >b.py
    printf 'def c():\n    return 3\n' >c.py
    git add -A
  )

  FAKE_HOME="$(mktemp -d "$BATS_TMPDIR/fakehome.XXXXXX")"
  STATE="$(make_deciding_reviewer_state "$FAKE_HOME")"
  HOME_BACKUP="${HOME:-}"
  TRELLIS_HOME_BACKUP="${TRELLIS_HOME:-}"
  export HOME="$FAKE_HOME"
  export TRELLIS_HOME="$FAKE_HOME/.trellis"
  unset CODE_REVIEWER_CMD TRELLIS_OMP_REVIEW_CMD OMP_ROLE_STATE
  export HERDR_ENV=1 HERDR_WORKSPACE_ID=fixture-workspace HERDR_PANE_ID=fixture-pane
  MARKER="$(mktemp "$BATS_TMPDIR/hookran.XXXXXX")"
  STUB_DIR="$(make_omp_stub "$MARKER")"
  PATH_BACKUP="$PATH"
  CLAUDE_DIR="$(make_tombstone_claude)"
  export PATH="$STUB_DIR:$CLAUDE_DIR:$PATH"
  export TRELLIS_OMP=1
  run_with_stderr "$HOOK" '{"stop_hook_active":false}'
  unset TRELLIS_OMP HERDR_ENV HERDR_WORKSPACE_ID HERDR_PANE_ID
  export PATH="$PATH_BACKUP"
  export HOME="$HOME_BACKUP"
  if [ -n "$TRELLIS_HOME_BACKUP" ]; then
    export TRELLIS_HOME="$TRELLIS_HOME_BACKUP"
  else
    unset TRELLIS_HOME
  fi
  RAN="$(cat "$MARKER" 2>/dev/null || true)"
  rm -rf "$FAKE_HOME" "$STUB_DIR" "$CLAUDE_DIR"
  rm -f "$MARKER"

  # Hook completed (exit 0) and reached the omp route…
  [ "$status" -eq 0 ]
  [[ "$RAN" == *RAN_OMP* ]] || { echo "expected the omp route to run; stderr: $stderr"; false; }
  # …and NO Claude process was ever spawned.
  [ ! -s "$TOMBSTONE" ] || { echo "CLAUSE REACHED:"; cat "$TOMBSTONE"; false; }
  teardown_tombstone
}

@test "code-review-subagent without TRELLIS_OMP keeps the canonical ladder (claude reachable)" {
  setup_project_dir
  setup_tombstone
  (
    cd "$PROJECT_DIR" || exit 1
    printf 'def a():\n    return 1\n' >a.py
    printf 'def b():\n    return 2\n' >b.py
    printf 'def c():\n    return 3\n' >c.py
    git add -A
  )

  # Sentinel forces the canonical ladder's deterministic rung; the point of
  # THIS test is only that the canonical lib (not omp-reviewer) was selected.
  CLAUDE_DIR="$(make_tombstone_claude)"
  PATH_BACKUP="$PATH"
  export PATH="$CLAUDE_DIR:$PATH"
  export TRELLIS_REVIEW_IN_PROGRESS=1
  unset TRELLIS_OMP || true
  run_with_stderr "$HOOK" '{"stop_hook_active":false}'
  unset TRELLIS_REVIEW_IN_PROGRESS
  export PATH="$PATH_BACKUP"

  [ "$status" -eq 0 ]
  # Deterministic rung on a secret-free diff → empty verdict; the hook emits
  # additionalContext only for non-empty advisories, so silence is expected.
  [ -z "$output" ] || [[ "$output" == *'"findings":'* ]] || { echo "GOT:[$output]"; false; }
  # The tombstone stays clean: the sentinel skipped the claude rung.
  [ ! -s "$TOMBSTONE" ] || { echo "CLAUDE REACHED:"; cat "$TOMBSTONE"; false; }
  teardown_tombstone
}
